version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
       - 5432:5432
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
  app1:
    container_name: app1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - redis
      - mongo
      - postgres
    volumes:
      - ./:/app
  app2:
    container_name: app2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    depends_on:
      - redis
      - mongo
      - postgres
    volumes:
      - ./:/app
  app3:
    container_name: app3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3003:3000
    depends_on:
      - redis
      - mongo
      - postgres
    volumes:
      - ./:/app
#  app4:
#    container_name: app4
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 3004:3000
#    depends_on:
#    - redis
#    - mongo
#    - postgres
#    volumes:
#      - ./:/app

  nginx:
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    image: nginx
    ports:
      - 8080:8080
    depends_on:
      - app1
      - app2
      - app3

