version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
  redis:
    container_name: redis
    image: redis:latest
    expose:
      - 6379
  mongo:
    container_name: mongo
    image: mongo:latest
    expose:
      - 27017
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
    - redis
    - mongo
    - postgres
    volumes:
      - ./:/app
